### ISSUE TITLE
Update link: Website...

### ISSUE THREAD

**Issue by Theli93** [maxkoryukov/headphones#34]
located in the bottom left-hand corner of web interface.

It still links to: https://github.com/rembo10/headphones

I've switched to your branch on my Synology, as it appears to be more actively developed. Sorry I don't have the skill-set to assist you, but I wish you good fortune on the endeavor!

Thank you.

**Comment by maxkoryukov** [comment]
confirmed

**Comment by maxkoryukov** [comment]
@Theli93, Thank you for your attention to this fork.

Here is tiny instructions for forks of the headphones: https://github.com/maxkoryukov/headphones/blob/master/README.md#about-this-fork

---

About your ticket: I think, that it is not fair to remove the link to the main website (currently, it is github page), so I just added another one link to the footer menu.

If you use master-branch from my fork with right configuration (described in the link above), then you could just run update for your HP installation through menu.

Thank you!

**Comment by maxkoryukov** [comment]
@Theli93 , and about my fork: I have added some features to the HP, but I won't maintain this repo for a long time, just bugfixes. The problem is that maintainers of the HP have paused the development of the upstream.. All features of this fork are already pull-requested to the mainstrean, and I am just waiting for the feedback..

So the best way is to get in touch with @rembo10, and ask him for approving of PRs
